/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuarterRouteImport } from './routes/quarter'
import { Route as TodayRouteImport } from './routes/today'
import { Route as WeekRouteImport } from './routes/week'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuarterRoute = QuarterRouteImport.update({
  id: '/quarter',
  path: '/quarter',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quarter': typeof QuarterRoute
  '/today': typeof TodayRoute
  '/week': typeof WeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quarter': typeof QuarterRoute
  '/today': typeof TodayRoute
  '/week': typeof WeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quarter': typeof QuarterRoute
  '/today': typeof TodayRoute
  '/week': typeof WeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quarter' | '/today' | '/week'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quarter' | '/today' | '/week'
  id: '__root__' | '/' | '/quarter' | '/today' | '/week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuarterRoute: typeof QuarterRoute
  TodayRoute: typeof TodayRoute
  WeekRoute: typeof WeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarter': {
      id: '/quarter'
      path: '/quarter'
      fullPath: '/quarter'
      preLoaderRoute: typeof QuarterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuarterRoute: QuarterRoute,
  TodayRoute: TodayRoute,
  WeekRoute: WeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
